# Generated by Django 3.2.2 on 2021-06-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
